import { Geist, Geist_Mono } from "next/font/google";
import { Kaisei_Tokumin } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kaiseiTokumin = Kaisei_Tokumin({
  variable: "--font-kaisei-tokumin",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable}
          ${kaiseiTokumin.variable} 
          max-w-7xl 
          mx-auto 
          px-4
          font-kaisei-tokumin 
          antialiased
          `}
      >
        {children}
      </body>
    </html>
  );
}
